name: Check

on:
  pull_request: # Check Pull Requests

  push:
    branches:
      - master # Check branch after merge

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Run Gradle Wrapper Validation to verify the wrapper's checksum
  gradle-validation:
    name: Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # we don't know what commit the last tag was
          fetch-depth: 0

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3

  check:
    name: Check for Scala ${{ matrix.scala }}
    runs-on: ubuntu-latest
    needs: gradle-validation
    strategy:
      matrix:
        include:
          - scala: "2.13"
          - scala: "3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # we don't know what commit the last tag was
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '11'
          check-latest: true
          cache: 'gradle'

      - name: Check
        run: >-
          ./gradlew --no-daemon clean check -PscalaBinaryVersion=${{ matrix.scala }}

  finish:
    name: Finish
    needs: # Should be last
      - "check"
    uses: taymyr/.github/.github/workflows/rtm.yml@v1
